# 在规则组里出现过的组名，在代理组里面也要必须出现。

[[custom_groups]]
name = "🔰 节点选择"
type = "select"
rule = [
    "♻️ 自动选择",
    "[]REJECT",
    # REJECT 是指拒绝，当选中该项的话，该代理组对应
    # 的规则组所发出的请求，既不代理，也不直连，直接
    # 拒绝。
    "[]DIRECT",
    # DIRECT 顾名思义，就是直连了。
    ".*",
    # .* 代表的是所有的节点，必须要
]

# 该组 自动选择 必须要，可以自动测试节点延迟
[[custom_groups]]
name = "♻️ 自动选择"
type = "url-test"
# 自动选择 组的 type 必须为 url-test
rule = [
    ".*",
]
url = "http://www.gstatic.com/generate_204"
# 测试延迟的 URL，就保持默认即可
interval = 300
# 延迟超时，及超过 300 ms 时就显示该节点已超时，但并
# 不代表节点不能用。(除非是真的不能用了)


[[custom_groups]]
name = "📲 Telegram"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "📲 微软服务"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🎥 AbemaTV"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🎥 哔哩哔哩"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🎥 巴哈姆特"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🎥 Netflix"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🎥 ニコニコ動画"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    ".*",
]

[[custom_groups]]
name = "🌍 国外流量"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
    # 至于这里为什么不加上 .*，原因很简单，对于 国外
    # 流量，留个 节点选择 承接上面就对了，然后讲究一
    # 下仪式，再加上 REJECT 和 DIRECT 也挺合理的吧。
]

[[custom_groups]]
name = "🎯 国内直连"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
]

[[custom_groups]]
name = "⛔️ 广告拦截"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]REJECT",
    "[]DIRECT",
]